-- MySQL Script generated by MySQL Workbench
-- dom 27 nov 2016 19:57:25 CLST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db-phreportes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db-phreportes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-phreportes` DEFAULT CHARACTER SET utf8 ;
USE `db-phreportes` ;

-- -----------------------------------------------------
-- Table `db-phreportes`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-phreportes`.`contrato` (
  `idcontrato` INT NOT NULL,
  `fecha_ingreso` VARCHAR(45) NULL,
  `fecha_termino` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontrato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-phreportes`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-phreportes`.`persona` (
  `idpersona` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `rut` VARCHAR(45) NULL,
  `sueldo` VARCHAR(45) NOT NULL,
  `contrato_idcontrato` INT NOT NULL,
  `area` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `salud` VARCHAR(45) NULL,
  `afp` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersona`),
  INDEX `fk_persona_contrato1_idx` (`contrato_idcontrato` ASC),
  CONSTRAINT `fk_persona_contrato1`
    FOREIGN KEY (`contrato_idcontrato`)
    REFERENCES `db-phreportes`.`contrato` (`idcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-phreportes`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-phreportes`.`perfil` (
  `idperfil` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-phreportes`.`persona_has_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-phreportes`.`persona_has_perfil` (
  `persona_idpersona` INT NOT NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`persona_idpersona`, `perfil_idperfil`),
  INDEX `fk_persona_has_perfil_perfil1_idx` (`perfil_idperfil` ASC),
  INDEX `fk_persona_has_perfil_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_persona_has_perfil_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `db-phreportes`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_has_perfil_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `db-phreportes`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-phreportes`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-phreportes`.`asistencia` (
  `idasistencia` INT NOT NULL,
  `hora_entrada` VARCHAR(45) NULL,
  `hora_salida` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`idasistencia`),
  INDEX `fk_asistencia_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_asistencia_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `db-phreportes`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
